### ISSUE TITLE
RunningAverage malfunction when attached to multiple outputs

### ISSUE THREAD

**Issue by miguelvr** [pytorch/ignite#311]
I just verified in `examples/gan/dcgan.py` that if we attach multiple RunningAverages in a for loop, the value updated to all the metrics is the one corresponding to the last value in the for loop.

The code snippet:
```python
# attach running average 
monitoring_metrics = ['errD', 'errG', 'D_x', 'D_G_z1', 'D_G_z2']
for metric in 
    RunningAverage(alpha=alpha, output_transform=lambda x: x[metric]).attach(trainer, metric)
```

The values being printed in the progress bar (all the same):
```
D_G_z1=5.85e-03, D_G_z2=5.85e-03, D_x=5.85e-03, errD=5.85e-03, errG=5.85e-03 
```

I've check and the output values are correct. What is corrupted is the `engine.state.metrics` values

If you add the outputs without a for loop, it works fine...

```python
RunningAverage(alpha=alpha, output_transform=lambda x: x['errD']).attach(trainer, 'errD')
RunningAverage(alpha=alpha, output_transform=lambda x: x['errG']).attach(trainer, 'errG')
RunningAverage(alpha=alpha, output_transform=lambda x: x['D_x']).attach(trainer, 'D_x')
RunningAverage(alpha=alpha, output_transform=lambda x: x['D_G_z1']).attach(trainer, 'D_G_z1')
RunningAverage(alpha=alpha, output_transform=lambda x: x['D_G_z2']).attach(trainer, 'D_G_z2')
```

**Comment by vfdev-5** [comment]
Thanks for catching this @miguelvr !

**Comment by vfdev-5** [comment]
Fixed by #312

**Comment by miguelvr** [comment]
@vfdev-5 my PR doesn't fix the issue. We should still look into it

**Comment by vfdev-5** [comment]
The problem is with `output_transform=lambda x: x[metric]` and especially with `metric` variable. Here is a snippet:
```python
funcs = []


monitoring_metrics = ['errD', 'errG', 'D_x', 'D_G_z1', 'D_G_z2']
for metric in monitoring_metrics:
    funcs.append(lambda x: metric)

for i, _ in enumerate(monitoring_metrics):
    print(funcs[i](0))

> D_G_z2
> D_G_z2
> D_G_z2
> D_G_z2
> D_G_z2
```
